import type { ICommands } from "@/shared/interfaces";

export const commands: ICommands = {
    help: [
        "#  ╔══════════════════════════════════════════════════════════╗",
        "#  ║                    Project Automata                      ║",
        "#  ║                 Command Line Interface                   ║",
        "#  ╚══════════════════════════════════════════════════════════╝",
        "#",
        "#  BASIC COMMANDS",
        "#     info                    Display detailed information about the project",
        "#     clear                   Clear terminal screen",
        "#     main                    Return to main screen",
        "#     echo <text>             Print specified text to terminal",
        "#     help                    Show this help message",
        "#",
        "#  AGENT COMMANDS",
        "#     mcp [options]           Execute browser automation agent",
        "#         Options:",
        "#         -m=<model>          LLM model for execution (default: qwen3:0.6b)",
        "#         -ms=<number>        Maximum execution steps (default: 5)",
        "#",
        "#     rag                     Execute RAG agent (currently in development)",
        "#",
        "#  USAGE EXAMPLES",
        "#     $ mcp -m=qwen3:0.6b -ms=5",
        "#     Initialize agent with custom parameters, then enter your prompt",
        "#     $ mcp",
        "#     Initialize agent with default parameters",
        "#     $ echo Hello, Automata",
        "#     Outputs: Hello, Automata!",
        "#     $ clear",
        "#     Clears all terminal history",
        "#",
        "#  ADDITIONAL INFORMATION",
        "#     – Commands are case-sensitive",
        "#     – Use ↑/↓ arrows to navigate command history",
        "#     – Press Enter to execute commands",
        "#",
        "#  © 2026 Denis Tomskikh",
    ],
    info: [
        "#  ╔══════════════════════════════════════════════════════════╗",
        "#  ║                    Project Automata                      ║",
        "#  ║            Intelligent Automation Platform               ║",
        "#  ╚══════════════════════════════════════════════════════════╝",
        "#",
        "#  OVERVIEW",
        "#     Project Automata is a browser automation platform that combines",
        "#     Playwright with locally running LLMs through Ollama. Users can execute",
        "#     complex web tasks using natural language while all processing remains",
        "#     on their own infrastructure.",
        "#",
        "#  ARCHITECTURE",
        "#     The platform consists of two main components:",
        "#",
        "#     ├─ Web CLI Interface",
        "#     │      A terminal emulator for interacting with the automation agent.",
        "#     │      Supports basic commands, command history, and agent execution.",
        "#     │",
        "#     └─ Browser Automation Agent",
        "#            An intelligent agent built on the Model Context Protocol (MCP),",
        "#            Playwright, and Ollama. Translates natural language instructions",
        "#            into browser actions including navigation, clicking, typing,",
        "#            and text extraction.",
        "#",
        "#  KEY FEATURES",
        "#     – Privacy-First: all processing happens locally, no data leaves",
        "#       your infrastructure",
        "#     – Natural Language Control: describe tasks in plain English",
        "#     – Extensible: add new browser actions by extending the toolset",
        "#     – Visual Feedback: screenshot support for page state verification",
        "#",
        "#  TECHNOLOGY STACK",
        "#     – Frontend: Vue 3 with TypeScript",
        "#     – Backend: Python with FastAPI",
        "#     – Browser Automation: Playwright",
        "#     – LLM Integration: Ollama (Local Models)",
        "#     – Tool Protocol: MCP (Model Context Protocol)",
        "#",
        "#  USE CASES",
        "#     – Automated web testing and QA",
        "#     – Data extraction and web scraping",
        "#     – RPA (Robotic Process Automation) alternatives",
        "#     – Development workflow automation",
        "#     – Research and data collection",
        "#",
        "#  GETTING STARTED",
        "#     1. Type 'help' to see available commands",
        "#     2. Pull an Ollama model: ollama pull qwen3:0.6b",
        "#     3. Start the agent with 'mcp' and enter your task",
        "#",
        "#  LICENSE",
        "#     Licensed under Apache License 2.0",
        "#     This means you can freely use, modify, and distribute the software,",
        "#     even for commercial purposes, while maintaining patent protection",
        "#     and contributing back improvements.",
        "#",
        "#  CONNECT WITH THE CREATOR",
        "#     – Creator: Denis Tomskikh",
        "#     – Email: tomskikh.denis@gmail.com",
        "#     – GitHub: https://github.com/whirlvoid",
        "#",
        "#  © 2026 Denis Tomskikh",
    ],
    clear: [""],
    main: [""],
    echo: [""],
    mcp: [""],
    rag: [""],
};